# Generated by Django 6.0.5 on 2026-10-02 12:39

from django.db import migrations, models

# Названия ролей, по которым раньше проверялись права, → новый уровень доступа
NAME_TO_CODE = {
    'администратор':   'admin',
    'руководитель':    'manager',
    'редактор':        'editor',
    'читатель':        'reader',
    'сторонний отдел': 'external',
}


def fill_codes(apps, schema_editor):
    Role = apps.get_model('support', 'Role')
    used = set()
    for role in Role.objects.order_by('id'):
        code = NAME_TO_CODE.get(role.name.strip().lower())
        if code and code not in used:
            role.code = code
            role.save(update_fields=['code'])
            used.add(code)


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0002_employee_proxy"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="code",
            field=models.CharField(
                blank=True,
                choices=[
                    ("admin", "Администратор"),
                    ("manager", "Руководитель"),
                    ("editor", "Редактор"),
                    ("reader", "Читатель"),
                    ("external", "Сторонний отдел"),
                ],
                help_text="Определяет права на сайте. Название роли можно менять свободно — права от него не зависят.",
                max_length=20,
                null=True,
                unique=True,
                verbose_name="Уровень доступа",
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="name",
            field=models.CharField(max_length=150, verbose_name="Название"),
        ),
        migrations.RunPython(fill_codes, migrations.RunPython.noop),
    ]
