# Generated by Django 6.0.5 on 2026-07-16 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrewMember',
            fields=[
                ('sap_number', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Табельный номер (SAP)')),
                ('first_name_ru', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя (RU)')),
                ('first_name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя (EN)')),
                ('second_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Фамилия')),
                ('full_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Полное ФИО')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Член экипажа',
                'verbose_name_plural': 'Члены экипажа',
                'ordering': ['-created_at'],
            },
        ),
    ]
