# Generated by Django 6.0.5 on 2026-10-02 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MicrositeProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Активный"),
                            ("closed", "Закрыт"),
                            ("archived", "В архиве"),
                        ],
                        default="active",
                        max_length=10,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
            ],
            options={
                "verbose_name": "Проект (микросайты)",
                "verbose_name_plural": "Проекты (микросайты)",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="PriceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160, verbose_name="Услуга")),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Цена, ₽",
                    ),
                ),
                (
                    "is_negotiable",
                    models.BooleanField(
                        default=False, verbose_name="По договорённости"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_items",
                        to="project_finance.micrositeproject",
                        verbose_name="Проект",
                    ),
                ),
            ],
            options={
                "verbose_name": "Позиция прайса",
                "verbose_name_plural": "Прайс-лист",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField(verbose_name="№")),
                ("title", models.CharField(max_length=200, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "service_name",
                    models.CharField(
                        blank=True,
                        max_length=160,
                        verbose_name="Услуга (на момент создания)",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Цена за единицу, ₽",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="Количество"),
                ),
                (
                    "time_spent",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="Затраченное время"
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата")),
                (
                    "is_free",
                    models.BooleanField(
                        default=False, verbose_name="Не включать в стоимость"
                    ),
                ),
                (
                    "is_paid",
                    models.BooleanField(default=False, verbose_name="Оплачено"),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата оплаты"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "price_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks",
                        to="project_finance.priceitem",
                        verbose_name="Услуга из прайса",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="project_finance.micrositeproject",
                        verbose_name="Проект",
                    ),
                ),
            ],
            options={
                "verbose_name": "Задача",
                "verbose_name_plural": "Задачи",
                "ordering": ["number"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("project", "number"), name="pf_task_unique_number"
                    )
                ],
            },
        ),
    ]
