# Generated by Django 6.0.5 on 2026-06-04 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст вопроса')),
                ('question_type', models.CharField(choices=[('text', 'Текстовый ответ'), ('choice', 'Выбор варианта')], default='text', max_length=10, verbose_name='Тип вопроса')),
                ('multiple', models.BooleanField(default=True, help_text='Если включено — используются чекбоксы, иначе — радиокнопки', verbose_name='Несколько правильных ответов')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ['category', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TestCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название категории')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, help_text='Отображать категорию на странице тестирования', verbose_name='Активна')),
                ('notify_email_main', models.EmailField(blank=True, help_text='На этот адрес придёт письмо (в поле «Кому»)', max_length=254, verbose_name='Основной получатель отчёта')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Категория тестирования',
                'verbose_name_plural': 'Категории тестирования',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AnswerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Текст варианта')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Правильный ответ')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='knowledge_check.question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Вариант ответа',
                'verbose_name_plural': 'Варианты ответов',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='knowledge_check.testcategory', verbose_name='Категория'),
        ),
        migrations.CreateModel(
            name='NotifyRecipientCC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email (копия)')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='Имя (необязательно)')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cc_recipients', to='knowledge_check.testcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Получатель копии',
                'verbose_name_plural': 'Получатели копии',
            },
        ),
        migrations.CreateModel(
            name='UserAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'В процессе'), ('completed', 'Завершено')], default='in_progress', max_length=20, verbose_name='Статус')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Начало')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершение')),
                ('email_sent', models.BooleanField(default=False, verbose_name='Отчёт отправлен')),
                ('retake_allowed', models.BooleanField(default=False, help_text='Если включено — сотрудник может пройти категорию заново', verbose_name='Разрешено повторное прохождение')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='knowledge_check.testcategory', verbose_name='Категория')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kc_attempts', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Попытка прохождения',
                'verbose_name_plural': 'Попытки прохождения',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True, verbose_name='Текстовый ответ')),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('chosen_options', models.ManyToManyField(blank=True, to='knowledge_check.answeroption', verbose_name='Выбранные варианты')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledge_check.question', verbose_name='Вопрос')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='knowledge_check.userattempt', verbose_name='Попытка')),
            ],
            options={
                'verbose_name': 'Ответ сотрудника',
                'verbose_name_plural': 'Ответы сотрудников',
                'ordering': ['answered_at'],
            },
        ),
        migrations.CreateModel(
            name='RetakeProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Разрешение повторного прохождения',
                'verbose_name_plural': 'Разрешения повторного прохождения',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('knowledge_check.userattempt',),
        ),
    ]
