# Generated by Django 6.0.5 on 2026-06-04 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_check', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='knowledge_check/attachments/', verbose_name='Файл')),
                ('caption', models.CharField(blank=True, help_text='Необязательное описание файла', max_length=255, verbose_name='Подпись')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='knowledge_check.question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Вложение к вопросу',
                'verbose_name_plural': 'Вложения к вопросам',
                'ordering': ['order', 'uploaded_at'],
            },
        ),
    ]
