# Generated by Django 6.0.5 on 2026-06-02 12:59

import aeroflot.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BdAeroflotArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('title', models.CharField(max_length=255, verbose_name='Название статьи')),
                ('content', models.TextField(verbose_name='Содержание статьи')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('views_count', models.IntegerField(default=0, verbose_name='Количество просмотров')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bdafl_created_articles', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('last_editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bdafl_edited_articles', to=settings.AUTH_USER_MODEL, verbose_name='Последний редактор')),
            ],
            options={
                'verbose_name': 'Статья БЗ Аэрофлот',
                'verbose_name_plural': 'Статьи БЗ Аэрофлот',
                'db_table': 'BdAeroflot_article',
                'ordering': ['-created_at'],
            },
            bases=(models.Model, aeroflot.models.MarkdownContentMixin),
        ),
        migrations.CreateModel(
            name='BdAeroflotAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='bdaeroflot_attachments/%Y/%m/%d/', validators=[aeroflot.models.validate_file_size], verbose_name='Файл')),
                ('file_name', models.CharField(max_length=255, verbose_name='Название файла')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='aeroflot.bdaeroflotarticle', verbose_name='Статья')),
            ],
            options={
                'verbose_name': 'Вложение БЗ Аэрофлот',
                'verbose_name_plural': 'Вложения БЗ Аэрофлот',
                'db_table': 'BdAeroflot_attachment',
            },
        ),
        migrations.CreateModel(
            name='BdAeroflotCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='Название категории')),
                ('description', models.TextField(blank=True, verbose_name='Описание категории')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bdafl_created_categories', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='aeroflot.bdaeroflotcategory', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Категория БЗ Аэрофлот',
                'verbose_name_plural': 'Категории БЗ Аэрофлот',
                'db_table': 'BdAeroflot_category',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='bdaeroflotarticle',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='aeroflot.bdaeroflotcategory', verbose_name='Категория'),
        ),
    ]
