# Generated by Django 6.0.5 on 2026-06-03 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aeroflot', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Создана'), ('updated', 'Изменена')], max_length=10, verbose_name='Действие')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_article_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Автор действия')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='aeroflot.bdaeroflotarticle', verbose_name='Статья')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Получатель')),
            ],
            options={
                'verbose_name': 'Уведомление о статье',
                'verbose_name_plural': 'Уведомления о статьях',
                'db_table': 'BdAeroflot_notification',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArticleAcknowledgement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acknowledged_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата ознакомления')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acknowledgements', to='aeroflot.bdaeroflotarticle', verbose_name='Статья')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_acknowledgements', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Ознакомление со статьёй',
                'verbose_name_plural': 'Ознакомления со статьями',
                'db_table': 'BdAeroflot_acknowledgement',
                'unique_together': {('article', 'user')},
            },
        ),
    ]
