# Generated by Django 6.0.5 on 2026-10-02 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aeroflot", "0002_articlenotification_articleacknowledgement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bdaeroflotattachment",
            name="article",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="aeroflot.bdaeroflotarticle",
                verbose_name="Статья",
            ),
        ),
    ]
