# Generated by Django 6.0.5 on 2026-05-28 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HelpdeskStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_ticket', models.IntegerField()),
                ('request_count_afl', models.IntegerField()),
                ('request_count_akr', models.IntegerField()),
                ('count_service_ife', models.IntegerField()),
                ('count_service_rportal', models.IntegerField()),
                ('redirect_second_line', models.FloatField()),
                ('avg_time_first_answer', models.FloatField(null=True)),
            ],
            options={
                'verbose_name': 'Статистика HelpDesk',
                'verbose_name_plural': 'Статистика HelpDesk',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HelpdeskCategoryAkr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('count', models.IntegerField()),
                ('statistic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories_akr', to='statistic.helpdeskstatistic')),
            ],
            options={
                'verbose_name': 'Категория AKR',
                'verbose_name_plural': 'Категории AKR',
                'ordering': ['-count'],
            },
        ),
        migrations.CreateModel(
            name='HelpdeskCategoryAfl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('count', models.IntegerField()),
                ('statistic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories_afl', to='statistic.helpdeskstatistic')),
            ],
            options={
                'verbose_name': 'Категория AFL',
                'verbose_name_plural': 'Категории AFL',
                'ordering': ['-count'],
            },
        ),
        migrations.CreateModel(
            name='HelpdeskAdminStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('count', models.IntegerField()),
                ('statistic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='statistic.helpdeskstatistic')),
            ],
            options={
                'verbose_name': 'Статистика по сотруднику',
                'verbose_name_plural': 'Статистика по сотрудникам',
                'ordering': ['-count'],
            },
        ),
    ]