# Generated by Django 6.0.5 on 2026-09-29 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0002_helpdeskcategoryafl_ticket_ids_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpdeskstatistic',
            name='redirect_second_line_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='HelpdeskTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline', models.CharField(choices=[('afl', 'ПАО "Аэрофлот"'), ('akr', 'АК "Россия"')], max_length=3)),
                ('ticket_id', models.PositiveIntegerField(null=True)),
                ('service_name', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(blank=True, max_length=255)),
                ('group', models.CharField(blank=True, max_length=255)),
                ('executor', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(null=True)),
                ('first_answer_at', models.DateTimeField(null=True)),
                ('first_answer_minutes', models.FloatField(null=True)),
                ('statistic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='statistic.helpdeskstatistic')),
            ],
            options={
                'verbose_name': 'Заявка HelpDesk',
                'verbose_name_plural': 'Заявки HelpDesk',
                'ordering': ['created_at', 'ticket_id'],
                'indexes': [models.Index(fields=['statistic', 'airline'], name='statistic_h_statist_98b1cb_idx')],
            },
        ),
    ]
