# Generated by Django 6.0.5 on 2026-06-02 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('status', models.CharField(choices=[('working', 'ЯП — Рабочий день'), ('working_holiday', 'РВ — Работа в выходной'), ('vacation', 'В — Выходной/отпуск')], max_length=20, verbose_name='Статус')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_entries', to='support.employeeprofile', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Запись табеля',
                'verbose_name_plural': 'Записи табеля',
                'ordering': ['date', 'employee'],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
