# Generated by Django 6.0.5 on 2026-07-17 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrewMember',
            fields=[
                ('sap_number', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Табельный номер')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя (с отчеством, RU)')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Фамилия (RU)')),
                ('full_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Полное ФИО (RU)')),
                ('full_name_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Полное ФИО (EN, транслит)')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email')),
                ('instructor_check', models.CharField(blank=True, max_length=100, null=True, verbose_name='ФИО инструкторской проверки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Член экипажа',
                'verbose_name_plural': 'Члены экипажа',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('document_number', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='Номер документа')),
                ('fake_document_number', models.CharField(blank=True, max_length=64, null=True, verbose_name='Фейковый номер документа')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Фамилия')),
                ('birth_date', models.CharField(blank=True, max_length=32, null=True, verbose_name='Дата рождения')),
                ('expiry_date', models.CharField(blank=True, max_length=32, null=True, verbose_name='Дата истечения документа')),
                ('phone_number', models.CharField(blank=True, max_length=64, null=True, verbose_name='Телефон (PCTC)')),
                ('ctcm_phone_number', models.CharField(blank=True, max_length=64, null=True, verbose_name='Телефон (CTCM)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Пассажир',
                'verbose_name_plural': 'Пассажиры',
                'ordering': ['-created_at'],
            },
        ),
    ]
