# Generated by Django 6.0.5 on 2026-06-03 13:26

import django.db.models.deletion
import russia.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BdRussiaArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('title', models.CharField(max_length=255, verbose_name='Название статьи')),
                ('content', models.TextField(verbose_name='Содержание статьи')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('views_count', models.IntegerField(default=0, verbose_name='Количество просмотров')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bdrussia_created_articles', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('last_editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bdrussia_edited_articles', to=settings.AUTH_USER_MODEL, verbose_name='Последний редактор')),
            ],
            options={
                'verbose_name': 'Статья БЗ Россия',
                'verbose_name_plural': 'Статьи БЗ Россия',
                'db_table': 'BdRussia_article',
                'ordering': ['-created_at'],
            },
            bases=(models.Model, russia.models.MarkdownContentMixin),
        ),
        migrations.CreateModel(
            name='BdRussiaAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='bdrussia_attachments/%Y/%m/%d/', validators=[russia.models.validate_file_size], verbose_name='Файл')),
                ('file_name', models.CharField(max_length=255, verbose_name='Название файла')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='russia.bdrussiaarticle', verbose_name='Статья')),
            ],
            options={
                'verbose_name': 'Вложение БЗ Россия',
                'verbose_name_plural': 'Вложения БЗ Россия',
                'db_table': 'BdRussia_attachment',
            },
        ),
        migrations.CreateModel(
            name='BdRussiaCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='Название категории')),
                ('description', models.TextField(blank=True, verbose_name='Описание категории')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bdrussia_created_categories', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='russia.bdrussiacategory', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Категория БЗ Россия',
                'verbose_name_plural': 'Категории БЗ Россия',
                'db_table': 'BdRussia_category',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='bdrussiaarticle',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='russia.bdrussiacategory', verbose_name='Категория'),
        ),
        migrations.CreateModel(
            name='RussiaArticleNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Создана'), ('updated', 'Изменена')], max_length=10, verbose_name='Действие')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='russia_sent_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Автор действия')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='russia.bdrussiaarticle', verbose_name='Статья')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='russia_article_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Получатель')),
            ],
            options={
                'verbose_name': 'Уведомление о статье Россия',
                'verbose_name_plural': 'Уведомления о статьях Россия',
                'db_table': 'BdRussia_notification',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RussiaArticleAcknowledgement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acknowledged_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата ознакомления')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acknowledgements', to='russia.bdrussiaarticle', verbose_name='Статья')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='russia_article_acknowledgements', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Ознакомление со статьёй',
                'verbose_name_plural': 'Ознакомления со статьями',
                'db_table': 'BdRussia_acknowledgement',
                'unique_together': {('article', 'user')},
            },
        ),
    ]
